"""initial schema

Revision ID: 64874dd3486c
Revises: 
Create Date: 2026-05-13 11:42:11.514962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64874dd3486c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_rate_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rate_24k', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gold_history_fetched_at', 'gold_rate_history', ['fetched_at'], unique=False)
    op.create_table('gold_rate_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rate_24k', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('set_by', sa.String(), nullable=False),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gold_override_active', 'gold_rate_overrides', ['is_active'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('karat', sa.Enum('K18', 'K21', 'K24', name='karat_enum'), nullable=False),
    sa.Column('weight_grams', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('making_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_products_category_karat', 'products', ['category', 'karat'], unique=False)
    op.create_index('ix_products_code', 'products', ['code'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_name_ar', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('vat_number', sa.String(), nullable=True),
    sa.Column('default_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_making_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lbp_exchange_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('receipt_footer', sa.String(), nullable=True),
    sa.Column('gold_refresh_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CASHIER', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'REFUNDED', 'VOIDED', name='orderstatus_enum'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CARD', 'MIXED', name='paymentmethod_enum'), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('cashier_id', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_lbp', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lbp_exchange_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.String(), nullable=True),
    sa.Column('void_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index('ix_orders_cashier', 'orders', ['cashier_id'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('karat', sa.Enum('K18', 'K21', 'K24', name='karat_enum'), nullable=False),
    sa.Column('weight_grams', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('gold_rate_at_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('making_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_cashier', table_name='orders')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index('ix_products_code', table_name='products')
    op.drop_index('ix_products_category_karat', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_gold_override_active', table_name='gold_rate_overrides')
    op.drop_table('gold_rate_overrides')
    op.drop_index('ix_gold_history_fetched_at', table_name='gold_rate_history')
    op.drop_table('gold_rate_history')
    # ### end Alembic commands ###
